# Generated by Django 5.0.2 on 2024-03-15 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='academixapp.unit'),
        ),
    ]
