# Generated by Django 5.0.2 on 2024-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academixapp', '0002_alter_subtopic_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.CharField(default='FY', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_branch',
            field=models.CharField(default='COMPSA', max_length=100),
        ),
    ]
