# Generated by Django 5.0.2 on 2024-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academixapp', '0004_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
    ]
