# Generated by Django 5.0.2 on 2024-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academixapp', '0011_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_lectures',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='course_tutorial',
            field=models.IntegerField(default=0),
        ),
    ]
