# Generated by Django 5.0.2 on 2024-03-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='user_images/'),
        ),
    ]
