# Generated by Django 5.0.2 on 2024-03-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('TEACHER', 'teacher')], default='', max_length=10),
        ),
    ]
