# Generated by Django 5.0.2 on 2024-03-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academixapp', '0009_alter_subtopicstatus_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopicstatus',
            name='subtopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academixapp.subtopic'),
        ),
    ]
